[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.poetry]
name = "pychecks"
version = "0.1.0"
description = "A simple checks framework"
authors = ["Scott Wilson <scott@propersquid.com>"]
license = "Apache-2.0"
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.7"

[tool.poetry.group.dev.dependencies]
pytest = "^7.4.2"
pytest-xdist = "^3.4.0"
pytest-cov = "^4.1.0"
hypothesis = "^6.79.4"
sphinx = "^5.3.0"
sphinx-rtd-theme = "^1.3.0"
myst-parser = "^1.0.0"
pytest-asyncio = "^0.21.1"
