[package]
name = "cchecks"
version = "0.1.0"
edition = "2021"
license = "MIT OR Apache-2.0"

[lib]
name = "cchecks"
crate-type = ["staticlib", "cdylib", "lib"]

[profile.release]
panic = "abort"

[profile.dev]
panic = "abort"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
checks = { path = "../../" }
bitflags = "2.0.0"
libc = "0.2.138"

[build-dependencies]
cbindgen = "0.25.0"

[dev-dependencies]
lazy_static = "1.4.0"
